{"timestamp":"2025-08-12T14:13:26.527596","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-12T14:13:26.540337","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-12T14:13:26.859728Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:26.871873Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:26.887629Z","level":"info","event":"Current task name:load_ratings","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:26.889661Z","level":"info","event":"Dag name:csv_ingestion_split_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:51.695837","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server on socket \"/var/run/postgresql/.s.PGSQL.5432\" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/modules/load_data.py","lineno":42,"name":"load_csv_to_postgres"},{"filename":"/opt/airflow/modules/load_data.py","lineno":9,"name":"get_postgres_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}]}]}
{"timestamp":"2025-08-12T14:13:51.703284Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:51.704098Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:51.704754Z","level":"info","event":"Task:<Task(PythonOperator): load_ratings>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:51.705261Z","level":"info","event":"Failure caused by connection to server on socket \"/var/run/postgresql/.s.PGSQL.5432\" failed: No such file or directory","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:51.705800Z","level":"info","event":"\tIs the server running locally and accepting connections on that socket?","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-12T14:13:51.706589Z","level":"info","event":"","chan":"stdout","logger":"task"}
